#encoding: utf-8
puts 'CREATING ROLES'
Role.delete_all
Role.create([
  { :name => 'admin' }, 
  { :name => 'user' },
  { :name => 'guest' }
], :without_protection => true)

puts 'SETTING UP DEFAULT USER LOGIN'
User.delete_all
user = User.create! :name => 'First User', :email => 'user@example.com', :password => 'please123', :password_confirmation => 'please123'
puts 'New user created: ' << user.name
user2 = User.create! :name => 'Second User', :email => 'user2@example.com', :password => 'please123', :password_confirmation => 'please123'
puts 'New user created: ' << user2.name
user.add_role :admin
user2.add_role :user

# Faculties
puts 'Start adding faculties'
Faculty.delete_all
# Faculty.reset_pk_sequence
ADF = Faculty.create!(
    :id => 1,
    :name => 'Автодорожный факультет',
    :url => 'http://s-vfu.ru/universitet/rukovodstvo-i-struktura/instituty/adf')
BGF = Faculty.create!(
    :id => 2,
    :name => 'Биолого-географический факультет',
    :url => 'http://s-vfu.ru/universitet/rukovodstvo-i-struktura/instituty/bgf')
GRF = Faculty.create!(
    :id => 3,
    :name => 'Геологоразведочный факультет',
    :url => 'http://s-vfu.ru/universitet/rukovodstvo-i-struktura/instituty/grf')
GF = Faculty.create!(
    :id => 4,
    :name => 'Горный факультет',
    :url => 'http://s-vfu.ru/universitet/rukovodstvo-i-struktura/instituty/gf')
ITI = Faculty.create!(
    :id => 5,
    :name => 'Инженерно-технический институт',
    :url => 'http://s-vfu.ru/universitet/rukovodstvo-i-struktura/instituty/iti')
IZFIR = Faculty.create!(
    :id => 6,
    :name => 'Институт зарубежной филологии и регионоведения',
    :url => 'http://s-vfu.ru/universitet/rukovodstvo-i-struktura/instituty/izfir')
IMI = Faculty.create!(
    :id => 7,
    :name => 'Институт математики и информатики',
    :url => 'http://s-vfu.ru/universitet/rukovodstvo-i-struktura/instituty/imi')
IP = Faculty.create!(
    :id => 8,
    :name => 'Институт психологии',
    :url => 'http://s-vfu.ru/universitet/rukovodstvo-i-struktura/instituty/ip')
IFKIS = Faculty.create!(
    :id => 9,
    :name => 'Институт физической культуры и спорта',
    :url => 'http://s-vfu.ru/universitet/rukovodstvo-i-struktura/instituty/ifkis')
IYIKN = Faculty.create!(
    :id => 10,
    :name => 'Институт языков и культуры народов Северо-Востока РФ',
    :url => 'http://s-vfu.ru/universitet/rukovodstvo-i-struktura/instituty/iyikn')
IF = Faculty.create!(
    :id => 11,
    :name => 'Исторический факультет',
    :url => 'http://s-vfu.ru/universitet/rukovodstvo-i-struktura/instituty/if')
MI = Faculty.create!(
    :id => 12,
    :name => 'Медицинский институт',
    :url => 'http://s-vfu.ru/universitet/rukovodstvo-i-struktura/instituty/mi')
PI = Faculty.create!(
    :id => 13,
    :name => 'Педагогический институт',
    :url => 'http://s-vfu.ru/universitet/rukovodstvo-i-struktura/instituty/pi')
TI = Faculty.create!(
    :id => 14,
    :name => 'Технологический институт',
    :url => 'http://s-vfu.ru/universitet/rukovodstvo-i-struktura/instituty/ti')
FTI = Faculty.create!(
    :id => 15,
    :name => 'Физико-технический институт',
    :url => 'http://s-vfu.ru/universitet/rukovodstvo-i-struktura/instituty/fti')
FLF = Faculty.create!(
    :id => 16,
    :name => 'Филологический факультет',
    :url => 'http://s-vfu.ru/universitet/rukovodstvo-i-struktura/instituty/flf')
FEI = Faculty.create!(
    :id => 17,
    :name => 'Финансово-экономический институт',
    :url => 'http://s-vfu.ru/universitet/rukovodstvo-i-struktura/instituty/fei')
YF = Faculty.create!(
    :id => 18,
    :name => 'Юридический факультет',
    :url => 'http://s-vfu.ru/universitet/rukovodstvo-i-struktura/instituty/yf')
puts 'Stop adding faculties'
puts 'Start adding levels'
#Levels
Level.delete_all
# Level.reset_pk_sequence
Level.create([
    {:id => 1, :name => '1'},
    {:id => 2, :name => '2'},
    {:id => 3, :name => '3'},
    {:id => 4, :name => '4'},
    {:id => 5, :name => '5'},
    {:id => 6, :name => '6'},
    {:id => 7, :name => 'МАГ'}])
puts 'Stop adding levels'
puts 'Start adding teachers'
#Teachers
Teacher.delete_all
# Teacher.reset_pk_sequence
Teacher.create([
    {:id => 1, :fio => 'Попов С. В.'},
    {:id => 2, :fio => 'Егоров В. А.'},
    {:id => 3, :fio => 'Кутукова Л. Т.'},
    {:id => 4, :fio => 'Прохорова А. Е.'},
    {:id => 5, :fio => 'Хохолов В. Б.'},
    {:id => 6, :fio => 'Попова Т. С.'},
    {:id => 7, :fio => 'Шарин Е. Ф.'},
    {:id => 8, :fio => 'Антипин В. И.'},
    {:id => 9, :fio => 'Марков В. Г.'},
    {:id => 10, :fio => 'Николаев Н. Н.'},
    {:id => 11, :fio => 'Прокопьев А. В.'},
    {:id => 12, :fio => 'Афанасьев А. Н.'},
    {:id => 13, :fio => 'Бочарова И. Н.'},
    {:id => 14, :fio => 'Бубякин И. В.'},
    {:id => 15, :fio => 'Никитина Е. С.'},
    {:id => 16, :fio => 'Поисеева С. С.'},
    {:id => 17, :fio => 'Попов О. Н.'},
    {:id => 18, :fio => 'Сивцева В. В.'},
    {:id => 19, :fio => 'Слепцова А. Е.'},
    {:id => 20, :fio => 'Федотова М. Е.'},
    {:id => 21, :fio => 'Шамаев Э. И.'},
    {:id => 22, :fio => 'Егоров И. Е.'},
    {:id => 23, :fio => 'Григорьев М. П.'},
    {:id => 24, :fio => 'Иванова О. Ф.'},
    {:id => 25, :fio => 'Семенова Г. Е.'},
    {:id => 26, :fio => 'Тихонова И. М.'},
    {:id => 27, :fio => 'Неустроева Н. В.'},
    {:id => 28, :fio => 'Семенова Г. М.'},
    {:id => 29, :fio => 'Федоров В. Е.'},
    {:id => 30, :fio => 'Васильев М. Д.'},
    {:id => 31, :fio => 'Романов Н. А.'},
    {:id => 32, :fio => 'Старостин Н. П.'},
    {:id => 33, :fio => 'Хлуднев А. М.'},
    {:id => 34, :fio => 'Ефимова Е. С.'},
    {:id => 35, :fio => 'Матвеева О. И.'},
    {:id => 36, :fio => 'Трофимцев Ю. И.'},
    {:id => 37, :fio => 'Шадрин В. Ю.'},
    {:id => 38, :fio => 'Аммосова М. С.'},
    {:id => 39, :fio => 'Вихреева О. А.'},
    {:id => 41, :fio => 'Львов А. П.'},
    {:id => 42, :fio => 'Николаев В. Е.'},
    {:id => 43, :fio => 'Пермяков Г. П.'},
    {:id => 44, :fio => 'Пинигина Н. Р.'},
    {:id => 45, :fio => 'Половинкин Ю. Т.'},
    {:id => 46, :fio => 'Скрябин Д. Д.'},
    {:id => 47, :fio => 'Тарасова Г. И.'},
    {:id => 48, :fio => 'Халтанова М. М.'},
    {:id => 49, :fio => 'Чистяков М. Г.'},
    {:id => 50, :fio => 'Григорьева Е. В.'},
    {:id => 51, :fio => 'Филиппова М. П.'},
    {:id => 52, :fio => 'Фролов Г. Г.'},
    {:id => 53, :fio => 'Саввин А. С.'},
    {:id => 54, :fio => 'Шестакова Т. П.'},
    {:id => 55, :fio => 'Слепцова А. Б.'},
    {:id => 56, :fio => 'Шадрина А. И.'},
    {:id => 57, :fio => 'Иванов Г. И.'},
    {:id => 58, :fio => 'Аргунова Н. В.'},
    {:id => 59, :fio => 'Анисимова К. А.'},
    {:id => 60, :fio => 'Афанасьев А. Е.'},
    {:id => 61, :fio => 'Ефремов В. П.'},
    {:id => 62, :fio => 'Макарова С. М.'},
    {:id => 63, :fio => 'Петрова А. И.'},
    {:id => 64, :fio => 'Романова С. М.'},
    {:id => 65, :fio => 'Скрябина А. Г.'},
    {:id => 66, :fio => 'Попова А. М.'},
    {:id => 67, :fio => 'Терешкина Г. Д.'},
    {:id => 68, :fio => 'Винокурова С. З.'},
    {:id => 69, :fio => 'Никифорова С. М.'},
    {:id => 70, :fio => 'Федотова А. И.'},
    {:id => 71, :fio => 'Эверстова В. Н.'},
    {:id => 72, :fio => 'Гусев В. А.'},
    {:id => 73, :fio => 'Жирков Е. П.'},
    {:id => 74, :fio => 'Ильина Е. А.'},
    {:id => 75, :fio => 'Алексеев Н. К.'},
    {:id => 76, :fio => 'Акимов М. П.'},
    {:id => 77, :fio => 'Иванов Ф. В.'},
    {:id => 78, :fio => 'Ларионова И. Г.'},
    {:id => 79, :fio => 'Тимофеева Т. С.'},
    {:id => 80, :fio => 'Тихонова О. А.'},
    {:id => 81, :fio => 'Троева М. С.'},
    {:id => 82, :fio => 'Уваровская М. И.'},
    {:id => 83, :fio => 'Охлопков Н. М.'},
    {:id => 84, :fio => 'Охлопков Г. Н.'},
    {:id => 85, :fio => 'Егорова Е. Р.'},
    {:id => 86, :fio => 'Егоров Д. В.'},
    {:id => 87, :fio => 'Антонов Ю. С.'},
    {:id => 88, :fio => 'Винокурова Е. С.'},
    {:id => 89, :fio => 'Курилкина В. Н.'},
    {:id => 90, :fio => 'Николаева Н. В.'},
    {:id => 91, :fio => 'Павлов Е. Е.'},
    {:id => 92, :fio => 'Аитова И. В.'},
    {:id => 93, :fio => 'Высоких О. А.'},
    {:id => 94, :fio => 'Ким Л. П.'},
    {:id => 95, :fio => 'Мальков И. М.'},
    {:id => 96, :fio => 'Ситников С. И.'},
    {:id => 97, :fio => 'Васильева С. М.'},
    {:id => 98, :fio => 'Винокурова Л. И.'},
    {:id => 99, :fio => 'Рожина Е. С.'},
    {:id => 100, :fio => 'Петров Е. Е.'},
    {:id => 101, :fio => 'Мордовской С. Д.'},
    {:id => 102, :fio => 'Павлов А. В.'},
    {:id => 103, :fio => 'Павлова Н. В.'},
    {:id => 104, :fio => 'Эверстов В. В.'},
    {:id => 105, :fio => 'Леверьев В. С.'},
    {:id => 106, :fio => 'Павлов Н. Н.'}
    ])
puts 'Stop adding teachers'
puts 'Start adding groups'
#Group
Group.delete_all
# Group.reset_pk_sequence
IMI.groups.create([
    {:id => 1, :name => 'ИНФ-13', :level_id => 1},
    {:id => 2, :name => 'МО-13-1', :level_id => 1},
    {:id => 3, :name => 'МО-13-2', :level_id => 1},
    {:id => 4, :name => 'МПО-13-1', :level_id => 1},
    {:id => 5, :name => 'МПО-13-2', :level_id => 1},
    {:id => 6, :name => 'ПМ-13-1', :level_id => 1},
    {:id => 7, :name => 'ПМ-13-2', :level_id => 1},
    {:id => 8, :name => 'ПИ-13-1', :level_id => 1},
    {:id => 9, :name => 'ПИ-13-2', :level_id => 1},
    {:id => 10, :name => 'ФИИТ-13', :level_id => 1},
    {:id => 11, :name => 'ИВТ-13', :level_id => 1},
    {:id => 12, :name => 'ИНФ-12', :level_id => 2},
    {:id => 13, :name => 'МО-12-1', :level_id => 2},
    {:id => 14, :name => 'МО-12-2', :level_id => 2},
    {:id => 15, :name => 'МПО-12-1', :level_id => 2},
    {:id => 16, :name => 'МПО-12-2', :level_id => 2},
    {:id => 17, :name => 'ПМ-12-1', :level_id => 2},
    {:id => 18, :name => 'ПМ-12-2', :level_id => 2},
    {:id => 19, :name => 'ПИ-12-1', :level_id => 2},
    {:id => 20, :name => 'ПИ-12-2', :level_id => 2},
    {:id => 21, :name => 'ФИИТ-12', :level_id => 2},
    {:id => 22, :name => 'ИВТ-12', :level_id => 2},
    {:id => 12, :name => 'ИНФ-11', :level_id => 3},
    {:id => 13, :name => 'МО-11-1', :level_id => 3},
    {:id => 14, :name => 'МО-11-2', :level_id => 3},
    {:id => 15, :name => 'МПО-11-1', :level_id => 3},
    {:id => 16, :name => 'МПО-11-2', :level_id => 3},
    {:id => 17, :name => 'ПМ-11-1', :level_id => 3},
    {:id => 18, :name => 'ПМ-11-2', :level_id => 3},
    {:id => 19, :name => 'ПИ-11-1', :level_id => 3},
    {:id => 20, :name => 'ПИ-11-2', :level_id => 3},
    {:id => 21, :name => 'ФИИТ-11', :level_id => 3},
    {:id => 22, :name => 'ИВТ-11', :level_id => 3},
    {:id => 23, :name => 'ИНФ-10', :level_id => 4},
    {:id => 24, :name => 'МО-10', :level_id => 4},
    {:id => 25, :name => 'МПО-10-1', :level_id => 4},
    {:id => 26, :name => 'МПО-10-2', :level_id => 4},
    {:id => 27, :name => 'МПО-10-3', :level_id => 4},
    {:id => 28, :name => 'ПМ-10', :level_id => 4},
    {:id => 29, :name => 'ПМ-10Б', :level_id => 4},
    {:id => 30, :name => 'ПИЭ-10', :level_id => 4},
    {:id => 31, :name => 'ИТ-10', :level_id => 4},
    {:id => 32, :name => 'ИВТ-10', :level_id => 4},
    {:id => 33, :name => 'ПО-10', :level_id => 4},
    {:id => 34, :name => 'МПО-09-1', :level_id => 5},
    {:id => 35, :name => 'МО-09', :level_id => 5},
    {:id => 36, :name => 'МПО-09-2', :level_id => 5},
    {:id => 37, :name => 'ИНФ-09', :level_id => 5},
    {:id => 38, :name => 'МАГ-12-1', :level_id => 6},
    {:id => 39, :name => 'МАГ-12-2', :level_id => 6},
    {:id => 40, :name => 'МАГ-12-3', :level_id => 6},
    {:id => 41, :name => 'МАГ-13-1', :level_id => 6},
    {:id => 42, :name => 'МАГ-13-2', :level_id => 6},
    {:id => 43, :name => 'МАГ-13-3', :level_id => 6}
    ])
puts 'Stop adding groups'
puts 'Start adding pairs'
Pair.delete_all
# Pair.reset_pk_sequence
Pair.create([
    {:id => 1, :name => 1, :duration => '08:00 - 09:35'},
    {:id => 2, :name => 2, :duration => '09:50 - 11:25'},
    {:id => 3, :name => 3, :duration => '11:40 - 13:15'},
    {:id => 4, :name => 4, :duration => '14:00 - 15:35'},
    {:id => 5, :name => 5, :duration => '15:45 - 17:20'},
    {:id => 6, :name => 6, :duration => '17:30 - 19:05'}
    ])
puts 'Stop adding pairs'
puts 'Start adding weekdays'
Weekday.delete_all
# Weekday.reset_pk_sequence
Weekday.create([
    {:id => 1, :name => 'Понедельник'},
    {:id => 2, :name => 'Вторник'},
    {:id => 3, :name => 'Среда'},
    {:id => 4, :name => 'Четверг'},
    {:id => 5, :name => 'Пятница'},
    {:id => 6, :name => 'Суббота'},
    {:id => 7, :name => 'Воскресенье'}
    ])
puts 'Stop adding weekdays'
puts 'Start adding subjects'
Subject.delete_all
# Subject.reset_pk_sequence
Subject.create([
    {:id => 1, :name => 'Математический анализ'},
    {:id => 2, :name => 'ЭВМ и программирование'},
    {:id => 3, :name => 'Практикум по ЭВМ'},
    {:id => 4, :name => 'Возрастная анатомия'},
    {:id => 5, :name => 'Элементарная математика'},
    {:id => 6, :name => 'Иностранный язык'},
    {:id => 7, :name => 'Основы ЗОЖ'},
    {:id => 8, :name => 'Алгебра'},
    {:id => 9, :name => 'Аналитическая геометрия'},
    {:id => 10, :name => 'Языки и методы программирования'},
    {:id => 11, :name => 'Мультимедийное ПО'},
    {:id => 12, :name => 'Народы и культура циркумполярного мира'},
    {:id => 13, :name => 'Практикум по решению мат.задач'},
    {:id => 14, :name => 'Геометрия'},
    {:id => 15, :name => 'Психология'},
    {:id => 16, :name => 'Теория алгоритмов'},
    {:id => 17, :name => 'Возрастная психология и анатомия'},
    {:id => 18, :name => 'Педагогика'},
    {:id => 19, :name => 'Философия'},
    {:id => 20, :name => 'Программирование'},
    {:id => 21, :name => 'Алгебра и геометрия'},
    {:id => 22, :name => 'ОС, сети и интернет.технологии'},
    {:id => 23, :name => 'Основы мат.обработки информации'},
    {:id => 24, :name => 'Програм.обесп. ЭВМ'},
    {:id => 25, :name => 'Математический анализ и дифф.уравнения'},
    {:id => 26, :name => 'Базы данных'},
    {:id => 27, :name => 'БЖД'},
    {:id => 28, :name => 'Алгоритмы и алгоритм.языки'},
    {:id => 29, :name => 'Информационные технологии'},
    {:id => 30, :name => 'Издательские системы'},
    {:id => 31, :name => 'Системы компьютерной математики'},
    {:id => 32, :name => 'Основы информатики'},
    {:id => 33, :name => 'Региональная экономика'},
    {:id => 34, :name => 'Выч.системы, сети и телекомм.'},
    {:id => 35, :name => 'Информатика и программирование'},
    {:id => 36, :name => 'Экономическая теория'},
    {:id => 37, :name => 'Физическое воспитание'},
    {:id => 38, :name => 'Менеджмент и маркетинг'},
    {:id => 39, :name => 'История'},
    {:id => 40, :name => 'Математика'},
    {:id => 41, :name => 'Финансы и кредит'},
    {:id => 42, :name => 'Архитектура и ВС'},
    {:id => 43, :name => 'Физика'},
    {:id => 44, :name => 'Культурология'},
    {:id => 45, :name => 'Якутский язык и культура народов'},
    {:id => 46, :name => 'Компьютерные науки'},
    {:id => 47, :name => 'Основы программирования'},
    {:id => 48, :name => 'Дискретная математика'},
    {:id => 49, :name => 'Народы и культура ЦМ'},
    {:id => 50, :name => 'ЭВМ и ПУ'},
    {:id => 51, :name => 'ЭВМ и периферийные устройства'},
    {:id => 52, :name => 'Введение в специальность'},
    {:id => 53, :name => 'Тензорная дифф.геом'},
    {:id => 54, :name => 'ТФКП'},
    {:id => 55, :name => 'Дифф.геом и топология'},
    {:id => 56, :name => 'Фнукциональный анализ'},
    {:id => 57, :name => 'Многомерная дифф.геом.'},
    {:id => 58, :name => 'Методика обучения математики'},
    {:id => 59, :name => 'Методы и средства защиты инф.'},
    {:id => 60, :name => 'Практикум по решению задач на ЭВМ'},
    {:id => 61, :name => 'Мат.логика и ТА'},
    {:id => 62, :name => 'Элементарная математика'},
    {:id => 63, :name => 'Коммуникативный иностранный язык'},
    {:id => 64, :name => 'История математики'},
    {:id => 65, :name => 'Основы матем.обработки информ.'},
    {:id => 66, :name => 'Образ.право'},
    {:id => 67, :name => 'Экономика образования'},
    {:id => 68, :name => 'Система упр.БД'},
    {:id => 69, :name => 'Задачи на оптимизацию геом.'},
    {:id => 70, :name => 'Практикум по ЯиМП'},
    {:id => 71, :name => 'Архитектура компьютера'},
    {:id => 72, :name => 'Комплексный анализ'},
    {:id => 73, :name => 'Системы программирования'},
    {:id => 74, :name => 'Интеллектуальные ИС'},
    {:id => 75, :name => 'Теория вероятностей и МС'},
    {:id => 76, :name => 'Коммуникативный русский язык'},
    {:id => 77, :name => 'Высокоуров.методы ИиП'},
    {:id => 78, :name => 'Сист.архитектура'},
    {:id => 79, :name => 'Выч.математика в экон.расчетах'},
    {:id => 80, :name => 'Финансовая математика'},
    {:id => 81, :name => 'Актуарные расчеты'},
    {:id => 82, :name => 'Ситемная архитектура выч.систем'},
    {:id => 83, :name => 'Системная ахитектура ВС'},
    {:id => 84, :name => 'Структ. и алг.обработка данных'},
    {:id => 85, :name => 'Метрология'},
    {:id => 86, :name => 'Инж.и комп.графика'},
    {:id => 87, :name => 'Языки программирования и мет.трансляции'},
    {:id => 88, :name => 'Web-программирование'},
    {:id => 89, :name => 'Инж. и комп.графика'},
    {:id => 90, :name => 'Элементы ТФКП'},
    {:id => 91, :name => 'Основы безопасности ИТ'},
    {:id => 92, :name => 'Орган.систем и ЭВМ'},
    {:id => 93, :name => 'Теория случ.процессов'},
    {:id => 94, :name => 'Психология и педагогика'},
    {:id => 95, :name => 'Графы, плоские графы'},
    {:id => 96, :name => 'Уравнения с частн.производными'},
    {:id => 97, :name => 'Основы геом.'},
    {:id => 98, :name => 'Теория чисел'},
    {:id => 99, :name => 'Менеджмент'},
    {:id => 100, :name => 'Психология делового общения'},
    {:id => 101, :name => 'Осн.методы и реш.ур-й и нер-в'},
    {:id => 102, :name => 'Изучение комбинаторики'},
    {:id => 103, :name => 'Задачи повышенной сложности'},
    {:id => 104, :name => 'Комп.сети,интернет и мультимедиа технологии'},
    {:id => 105, :name => 'Культура народов Якутии'},
    {:id => 106, :name => 'Русский язык'},
    {:id => 107, :name => 'Английский для науч.раб.'},
    {:id => 108, :name => 'Основы паралл.программирования'},
    {:id => 109, :name => 'Основы АИТ в БУ'},
    {:id => 110, :name => 'Теория конечных графов и ее прил.'},
    {:id => 111, :name => 'Методы оптим. и исслед.операций'},
    {:id => 112, :name => 'Автома.реш.учетных задач'},
    {:id => 113, :name => 'Програмная инженерия'},
    {:id => 114, :name => 'Программирование .NET'},
    {:id => 115, :name => 'Эконометрика'},
    {:id => 116, :name => 'Теория систем и системный анализ'},
    {:id => 117, :name => 'Теория принятий решения'},
    {:id => 118, :name => 'Сети ЭВМ и ТК'},
    {:id => 119, :name => 'Ассемблер'},
    {:id => 120, :name => 'Функц. и логич. програм.'},
    {:id => 121, :name => 'Организация ЭВМ и систем'},
    {:id => 122, :name => 'Пак.прикл.прог.'},
    {:id => 123, :name => 'Язык приложений'},
    {:id => 124, :name => 'Схемотехника ЭВМ'},
    {:id => 125, :name => 'Язык запросов SQL'},
    {:id => 126, :name => 'Электротехника и электроника'},
    {:id => 127, :name => 'Нестандартные задачи'},
    {:id => 128, :name => 'Анализ учебных программ'},
    {:id => 129, :name => 'Управ.совр.школой'},
    {:id => 130, :name => 'ТиМОМ'},
    {:id => 131, :name => 'Метол.вопросы обучения математики'},
    {:id => 132, :name => 'Теоретическая механика'},
    {:id => 133, :name => 'Элементы истории математики в школьном курсе'},
    {:id => 134, :name => 'Система подготовки к выпускным экзаменам'},
    {:id => 135, :name => 'Предметные олимпиады'},
    {:id => 136, :name => 'ТиМОИ'},
    {:id => 137, :name => 'Архитектура компьютера'},
    {:id => 138, :name => 'ТРПО'},
    {:id => 139, :name => 'Об.-Ориент.программирование'},
    {:id => 140, :name => 'Исследование операций'},
    {:id => 141, :name => 'Основы м/электроники'},
    {:id => 142, :name => 'Комп.моделирование'},
    {:id => 143, :name => 'Численные методы в конф.управл.системах'},
    {:id => 144, :name => 'Теория игр и ИО'},
    {:id => 145, :name => 'Гидродинамика'},
    {:id => 146, :name => 'Сети ЭВМ и телекоммуникации'},
    {:id => 147, :name => 'Совр.комп.технологии'},
    {:id => 148, :name => 'Прикладная социология'},
    {:id => 149, :name => 'Введение в теорию разн.схем'},
    {:id => 150, :name => 'Этика дел.общения'},
    {:id => 151, :name => 'Организация и планирование производства'},
    {:id => 152, :name => 'Маркетинговые коммуникации'},
    {:id => 153, :name => 'Суперкомпьютеры'},
    {:id => 154, :name => 'Сетевое администрирование'},
    {:id => 155, :name => 'Социальные и этические вопросы'},
    {:id => 156, :name => 'Технологии разработки программного обеспечения'},
    {:id => 157, :name => 'Возрастная психология'},
    {:id => 158, :name => 'Сравнительная педагогика'},
    {:id => 159, :name => 'НИТ'},
    {:id => 160, :name => 'Мет. и техн. вед.урока'},
    {:id => 161, :name => 'Современные средства оценивания результатов'},
    {:id => 162, :name => 'Формирование познавательной активности учащихся гум.классов'},
    {:id => 163, :name => 'Орган.исслед.работы по МПМ'},
    {:id => 164, :name => 'Техника дист.обучения'},
    {:id => 165, :name => 'Защита информации в компьютерных системах'},
    {:id => 166, :name => 'Личн.развитие и ВЛК'},
    {:id => 167, :name => 'Дистанционные образ.технологии'},
    {:id => 168, :name => 'Методика тестирования'},
    {:id => 169, :name => 'Решение задач ЕГЭ'},
    {:id => 170, :name => 'Философия математики'},
    {:id => 171, :name => 'Методика препод.инф.в проф.классах'},
    {:id => 172, :name => 'Некот.классич.задачи'},
    {:id => 173, :name => 'Сетевые технологии'},
    {:id => 174, :name => 'Комп.технологии в в науке и образ.'},
    {:id => 175, :name => 'Философия и методология научного познания'},
    {:id => 176, :name => 'Применение ДУ в матем.и физике'},
    {:id => 177, :name => 'НИР'},
    {:id => 178, :name => 'Мат.методы УСС'},
    {:id => 179, :name => 'Вычислительная теория фильтр.'},
    {:id => 180, :name => 'Мат.модели в естествознании'},
    {:id => 181, :name => 'Оптим.управление в задачах матфизики'},
    {:id => 182, :name => 'Объективные базы данных'},
    {:id => 183, :name => 'Задачи динам.идеал.несж.жидк.'},
    {:id => 184, :name => 'Устойчивость в КУС'},
    {:id => 185, :name => 'Численные методы в зад.УТП'},
    {:id => 186, :name => 'Мат.моделирование в трибологии'},
    {:id => 187, :name => 'Числ.методы реш.некот.обр.задач'}
    ])
puts 'Stop adding subjects'
puts 'Start adding buildings'
Building.delete_all
# Building.reset_pk_sequence
Building.create([    
    {:id => 1, :name => 'КФЕН'},
    {:id => 2, :name => 'КТФ'},
    {:id => 3, :name => 'МИ'},
    {:id => 4, :name => 'КГФ'},
    {:id => 5, :name => 'УЛК'},
    {:id => 6, :name => 'ГУК'}
    ])
puts 'Stop adding buildings'
puts 'Start adding rooms'
Room.delete_all
# Room.reset_pk_sequence
Room.create([
    {:name => '324', :building_id => 1},
    {:name => '326', :building_id => 1},
    {:name => '328', :building_id => 1},
    {:name => '330', :building_id => 1},
    {:name => '349', :building_id => 1},
    {:name => '351', :building_id => 1},
    {:name => '353', :building_id => 1},
    {:name => '355', :building_id => 1},
    {:name => '357', :building_id => 1},
    {:name => '445', :building_id => 1},
    {:name => '447', :building_id => 1},
    {:name => '449', :building_id => 1},
    {:name => '451', :building_id => 1},
    {:name => '453', :building_id => 1},
    {:name => '455', :building_id => 1},
    {:name => '457', :building_id => 1},
    {:name => '424', :building_id => 1},
    {:name => '426', :building_id => 1},
    {:name => '430', :building_id => 1},
    {:name => '432', :building_id => 1},
    {:name => '436', :building_id => 1},
    {:name => '536', :building_id => 1},
    {:name => '540', :building_id => 1}
    ])
puts 'Stop adding rooms'
puts 'Start adding schedules'
Schedule.delete_all
# Schedule.reset_pk_sequence
Schedule.create([
    {:parity => 1, :weekday_id => 1, :pair_id => 1, :room_id => 1, :group_id => 2, :teacher_id => 1, :subject_id => 1, :occupation => ''},
    {:parity => 2, :weekday_id => 1, :pair_id => 2, :room_id => 1, :group_id => 2, :teacher_id => 1, :subject_id => 1, :occupation => ''},
    {:parity => 0, :weekday_id => 1, :pair_id => 2, :room_id => 1, :group_id => 2, :teacher_id => 2, :subject_id => 2, :occupation => ''},
    {:parity => 0, :weekday_id => 1, :pair_id => 3, :room_id => 1, :group_id => 2, :teacher_id => 3, :subject_id => 3, :occupation => ''}, 
    {:parity => 0, :weekday_id => 1, :pair_id => 4, :room_id => 1, :group_id => 2, :teacher_id => 4, :subject_id => 4, :occupation => ''},
    {:parity => 0, :weekday_id => 1, :pair_id => 1, :room_id => 1, :group_id => 1, :teacher_id => 5, :subject_id => 5, :occupation => ''},
    {:parity => 0, :weekday_id => 1, :pair_id => 2, :room_id => 1, :group_id => 1, :teacher_id => 6, :subject_id => 6, :occupation => ''},
    {:parity => 1, :weekday_id => 1, :pair_id => 3, :room_id => 1, :group_id => 1, :teacher_id => 6, :subject_id => 7, :occupation => ''},
    {:parity => 2, :weekday_id => 1, :pair_id => 3, :room_id => 6, :group_id => 1, :teacher_id => 10, :subject_id => 20, :occupation => ''},
    {:parity => 1, :weekday_id => 1, :pair_id => 4, :room_id => 4, :group_id => 1, :teacher_id => 7, :subject_id => 8, :occupation => ''},
    {:parity => 2, :weekday_id => 1, :pair_id => 4, :room_id => 3, :group_id => 1, :teacher_id => 3, :subject_id => 10, :occupation => ''},
    {:parity => 1, :weekday_id => 1, :pair_id => 1, :room_id => 1, :group_id => 3, :teacher_id => 8, :subject_id => 9, :occupation => ''},
    {:parity => 2, :weekday_id => 1, :pair_id => 3, :room_id => 1, :group_id => 3, :teacher_id => 8, :subject_id => 9, :occupation => ''},
    {:parity => 1, :weekday_id => 1, :pair_id => 2, :room_id => 1, :group_id => 3, :teacher_id => 9, :subject_id => 10, :occupation => ''},
    {:parity => 2, :weekday_id => 1, :pair_id => 3, :room_id => 1, :group_id => 3, :teacher_id => 9, :subject_id => 10, :occupation => ''},
    {:parity => 1, :weekday_id => 1, :pair_id => 3, :room_id => 1, :group_id => 3, :teacher_id => 10, :subject_id => 11, :occupation => ''},
    {:parity => 2, :weekday_id => 1, :pair_id => 4, :room_id => 1, :group_id => 3, :teacher_id => 10, :subject_id => 11, :occupation => ''},
    {:parity => 1, :weekday_id => 1, :pair_id => 4, :room_id => 1, :group_id => 3, :teacher_id => 11, :subject_id => 12, :occupation => ''},
    {:parity => 2, :weekday_id => 1, :pair_id => 3, :room_id => 1, :group_id => 3, :teacher_id => 11, :subject_id => 12, :occupation => ''},
    {:parity => 1, :weekday_id => 1, :pair_id => 1, :room_id => 1, :group_id => 4, :teacher_id => 12, :subject_id => 13, :occupation => ''},
    {:parity => 2, :weekday_id => 1, :pair_id => 2, :room_id => 1, :group_id => 4, :teacher_id => 12, :subject_id => 13, :occupation => ''},
    {:parity => 0, :weekday_id => 1, :pair_id => 2, :room_id => 1, :group_id => 4, :teacher_id => 13, :subject_id => 14, :occupation => ''},
    {:parity => 0, :weekday_id => 1, :pair_id => 3, :room_id => 1, :group_id => 4, :teacher_id => 14, :subject_id => 15, :occupation => ''},
    {:parity => 0, :weekday_id => 1, :pair_id => 4, :room_id => 1, :group_id => 4, :teacher_id => 15, :subject_id => 16, :occupation => ''},
    {:parity => 0, :weekday_id => 1, :pair_id => 1, :room_id => 1, :group_id => 5, :teacher_id => 16, :subject_id => 17, :occupation => ''},
    {:parity => 0, :weekday_id => 1, :pair_id => 2, :room_id => 1, :group_id => 5, :teacher_id => 17, :subject_id => 18, :occupation => ''},
    {:parity => 0, :weekday_id => 1, :pair_id => 3, :room_id => 1, :group_id => 5, :teacher_id => 18, :subject_id => 19, :occupation => ''},
    {:parity => 0, :weekday_id => 1, :pair_id => 4, :room_id => 1, :group_id => 5, :teacher_id => 19, :subject_id => 20, :occupation => ''},
    {:parity => 0, :weekday_id => 1, :pair_id => 1, :room_id => 1, :group_id => 6, :teacher_id => 21, :subject_id => 21, :occupation => ''},
    {:parity => 0, :weekday_id => 1, :pair_id => 2, :room_id => 1, :group_id => 6, :teacher_id => 20, :subject_id => 22, :occupation => ''},
    {:parity => 0, :weekday_id => 1, :pair_id => 3, :room_id => 1, :group_id => 6, :teacher_id => 22, :subject_id => 23, :occupation => ''},
    {:parity => 0, :weekday_id => 1, :pair_id => 4, :room_id => 1, :group_id => 6, :teacher_id => 23, :subject_id => 24, :occupation => ''},
    {:parity => 0, :weekday_id => 2, :pair_id => 1, :room_id => 1, :group_id => 2, :teacher_id => 1, :subject_id => 1, :occupation => ''},
    {:parity => 0, :weekday_id => 2, :pair_id => 2, :room_id => 1, :group_id => 2, :teacher_id => 2, :subject_id => 2, :occupation => ''},
    {:parity => 0, :weekday_id => 2, :pair_id => 3, :room_id => 1, :group_id => 2, :teacher_id => 3, :subject_id => 3, :occupation => ''} , 
    {:parity => 0, :weekday_id => 2, :pair_id => 4, :room_id => 1, :group_id => 2, :teacher_id => 4, :subject_id => 4, :occupation => ''},
    {:parity => 0, :weekday_id => 2, :pair_id => 1, :room_id => 1, :group_id => 1, :teacher_id => 5, :subject_id => 5, :occupation => ''},
    {:parity => 0, :weekday_id => 2, :pair_id => 2, :room_id => 1, :group_id => 1, :teacher_id => 6, :subject_id => 6, :occupation => ''},
    {:parity => 0, :weekday_id => 2, :pair_id => 3, :room_id => 1, :group_id => 1, :teacher_id => 6, :subject_id => 7, :occupation => ''},
    {:parity => 0, :weekday_id => 2, :pair_id => 4, :room_id => 1, :group_id => 1, :teacher_id => 7, :subject_id => 8, :occupation => ''},
    {:parity => 0, :weekday_id => 2, :pair_id => 1, :room_id => 1, :group_id => 3, :teacher_id => 8, :subject_id => 9, :occupation => ''},
    {:parity => 0, :weekday_id => 2, :pair_id => 2, :room_id => 1, :group_id => 3, :teacher_id => 9, :subject_id => 10, :occupation => ''},
    {:parity => 0, :weekday_id => 2, :pair_id => 3, :room_id => 1, :group_id => 3, :teacher_id => 10, :subject_id => 11, :occupation => ''},
    {:parity => 0, :weekday_id => 2, :pair_id => 4, :room_id => 1, :group_id => 3, :teacher_id => 11, :subject_id => 12, :occupation => ''},
    {:parity => 0, :weekday_id => 2, :pair_id => 1, :room_id => 1, :group_id => 4, :teacher_id => 12, :subject_id => 13, :occupation => ''},
    {:parity => 0, :weekday_id => 2, :pair_id => 2, :room_id => 1, :group_id => 4, :teacher_id => 13, :subject_id => 14, :occupation => ''},
    {:parity => 0, :weekday_id => 2, :pair_id => 3, :room_id => 1, :group_id => 4, :teacher_id => 14, :subject_id => 15, :occupation => ''},
    {:parity => 0, :weekday_id => 2, :pair_id => 4, :room_id => 1, :group_id => 4, :teacher_id => 15, :subject_id => 16, :occupation => 'лаб.работа'},
    {:parity => 0, :weekday_id => 2, :pair_id => 1, :room_id => 1, :group_id => 5, :teacher_id => 16, :subject_id => 17, :occupation => 'лаб.работа'},
    {:parity => 0, :weekday_id => 2, :pair_id => 2, :room_id => 1, :group_id => 5, :teacher_id => 17, :subject_id => 18, :occupation => 'лаб.работа'},
    {:parity => 0, :weekday_id => 2, :pair_id => 3, :room_id => 1, :group_id => 5, :teacher_id => 18, :subject_id => 19, :occupation => 'лаб.работа'},
    {:parity => 0, :weekday_id => 2, :pair_id => 4, :room_id => 1, :group_id => 5, :teacher_id => 19, :subject_id => 20, :occupation => 'лаб.работа'},
    {:parity => 0, :weekday_id => 2, :pair_id => 1, :room_id => 1, :group_id => 6, :teacher_id => 21, :subject_id => 21, :occupation => 'лаб.работа'},
    {:parity => 0, :weekday_id => 2, :pair_id => 2, :room_id => 1, :group_id => 6, :teacher_id => 20, :subject_id => 22, :occupation => 'лаб.работа'},
    {:parity => 0, :weekday_id => 2, :pair_id => 3, :room_id => 1, :group_id => 6, :teacher_id => 22, :subject_id => 23, :occupation => 'лаб.работа'},
    {:parity => 0, :weekday_id => 2, :pair_id => 4, :room_id => 1, :group_id => 6, :teacher_id => 23, :subject_id => 24, :occupation => 'лаб.работа'},
    {:parity => 0, :weekday_id => 3, :pair_id => 1, :room_id => 1, :group_id => 2, :teacher_id => 1, :subject_id => 1, :occupation => ''},
    {:parity => 0, :weekday_id => 3, :pair_id => 2, :room_id => 1, :group_id => 2, :teacher_id => 2, :subject_id => 2, :occupation => ''},
    {:parity => 0, :weekday_id => 3, :pair_id => 3, :room_id => 1, :group_id => 2, :teacher_id => 3, :subject_id => 3, :occupation => ''} , 
    {:parity => 0, :weekday_id => 3, :pair_id => 4, :room_id => 1, :group_id => 2, :teacher_id => 4, :subject_id => 4, :occupation => ''},
    {:parity => 0, :weekday_id => 3, :pair_id => 1, :room_id => 1, :group_id => 1, :teacher_id => 5, :subject_id => 5, :occupation => ''},
    {:parity => 0, :weekday_id => 3, :pair_id => 2, :room_id => 1, :group_id => 1, :teacher_id => 6, :subject_id => 6, :occupation => 'лекция'},
    {:parity => 0, :weekday_id => 3, :pair_id => 3, :room_id => 1, :group_id => 1, :teacher_id => 6, :subject_id => 7, :occupation => 'лекция'},
    {:parity => 0, :weekday_id => 3, :pair_id => 4, :room_id => 1, :group_id => 1, :teacher_id => 7, :subject_id => 8, :occupation => 'лекция'},
    {:parity => 0, :weekday_id => 3, :pair_id => 1, :room_id => 1, :group_id => 3, :teacher_id => 8, :subject_id => 9, :occupation => 'лекция'},
    {:parity => 0, :weekday_id => 3, :pair_id => 2, :room_id => 1, :group_id => 3, :teacher_id => 9, :subject_id => 10, :occupation => 'лекция'},
    {:parity => 0, :weekday_id => 3, :pair_id => 3, :room_id => 1, :group_id => 3, :teacher_id => 10, :subject_id => 11, :occupation => 'лекция'},
    {:parity => 0, :weekday_id => 3, :pair_id => 4, :room_id => 1, :group_id => 3, :teacher_id => 11, :subject_id => 12, :occupation => 'лекция'},
    {:parity => 0, :weekday_id => 3, :pair_id => 1, :room_id => 1, :group_id => 4, :teacher_id => 12, :subject_id => 13, :occupation => 'лекция'},
    {:parity => 0, :weekday_id => 3, :pair_id => 2, :room_id => 1, :group_id => 4, :teacher_id => 13, :subject_id => 14, :occupation => 'лекция'},
    {:parity => 0, :weekday_id => 3, :pair_id => 3, :room_id => 1, :group_id => 4, :teacher_id => 14, :subject_id => 15, :occupation => 'лекция'},
    {:parity => 0, :weekday_id => 3, :pair_id => 4, :room_id => 1, :group_id => 4, :teacher_id => 15, :subject_id => 16, :occupation => ''},
    {:parity => 0, :weekday_id => 3, :pair_id => 1, :room_id => 1, :group_id => 5, :teacher_id => 16, :subject_id => 17, :occupation => ''},
    {:parity => 0, :weekday_id => 3, :pair_id => 2, :room_id => 1, :group_id => 5, :teacher_id => 17, :subject_id => 18, :occupation => ''},
    {:parity => 0, :weekday_id => 3, :pair_id => 3, :room_id => 1, :group_id => 5, :teacher_id => 18, :subject_id => 19, :occupation => ''},
    {:parity => 0, :weekday_id => 3, :pair_id => 4, :room_id => 1, :group_id => 5, :teacher_id => 19, :subject_id => 20, :occupation => ''},
    {:parity => 0, :weekday_id => 3, :pair_id => 1, :room_id => 1, :group_id => 6, :teacher_id => 21, :subject_id => 21, :occupation => ''},
    {:parity => 0, :weekday_id => 3, :pair_id => 2, :room_id => 1, :group_id => 6, :teacher_id => 20, :subject_id => 22, :occupation => ''},
    {:parity => 0, :weekday_id => 3, :pair_id => 3, :room_id => 1, :group_id => 6, :teacher_id => 22, :subject_id => 23, :occupation => ''},
    {:parity => 0, :weekday_id => 3, :pair_id => 4, :room_id => 1, :group_id => 6, :teacher_id => 23, :subject_id => 24, :occupation => ''},
    {:parity => 0, :weekday_id => 4, :pair_id => 1, :room_id => 1, :group_id => 2, :teacher_id => 1, :subject_id => 1, :occupation => 'практика'},
    {:parity => 0, :weekday_id => 4, :pair_id => 2, :room_id => 1, :group_id => 2, :teacher_id => 2, :subject_id => 2, :occupation => 'практика'},
    {:parity => 0, :weekday_id => 4, :pair_id => 3, :room_id => 1, :group_id => 2, :teacher_id => 3, :subject_id => 3, :occupation => 'практика'} , 
    {:parity => 0, :weekday_id => 4, :pair_id => 4, :room_id => 1, :group_id => 2, :teacher_id => 4, :subject_id => 4, :occupation => 'практика'},
    {:parity => 0, :weekday_id => 4, :pair_id => 1, :room_id => 1, :group_id => 1, :teacher_id => 5, :subject_id => 5, :occupation => 'практика'},
    {:parity => 0, :weekday_id => 4, :pair_id => 2, :room_id => 1, :group_id => 1, :teacher_id => 6, :subject_id => 6, :occupation => ''},
    {:parity => 0, :weekday_id => 4, :pair_id => 3, :room_id => 1, :group_id => 1, :teacher_id => 6, :subject_id => 7, :occupation => ''},
    {:parity => 0, :weekday_id => 4, :pair_id => 4, :room_id => 1, :group_id => 1, :teacher_id => 7, :subject_id => 8, :occupation => ''},
    {:parity => 0, :weekday_id => 4, :pair_id => 1, :room_id => 1, :group_id => 3, :teacher_id => 8, :subject_id => 9, :occupation => ''},
    {:parity => 0, :weekday_id => 4, :pair_id => 2, :room_id => 1, :group_id => 3, :teacher_id => 9, :subject_id => 10, :occupation => ''},
    {:parity => 0, :weekday_id => 4, :pair_id => 3, :room_id => 1, :group_id => 3, :teacher_id => 10, :subject_id => 11, :occupation => 'практика'},
    {:parity => 0, :weekday_id => 4, :pair_id => 4, :room_id => 1, :group_id => 3, :teacher_id => 11, :subject_id => 12, :occupation => 'практика'},
    {:parity => 0, :weekday_id => 4, :pair_id => 1, :room_id => 1, :group_id => 4, :teacher_id => 12, :subject_id => 13, :occupation => 'практика'},
    {:parity => 0, :weekday_id => 4, :pair_id => 2, :room_id => 1, :group_id => 4, :teacher_id => 13, :subject_id => 14, :occupation => 'практика'},
    {:parity => 0, :weekday_id => 4, :pair_id => 3, :room_id => 1, :group_id => 4, :teacher_id => 14, :subject_id => 15, :occupation => 'практика'},
    {:parity => 0, :weekday_id => 4, :pair_id => 4, :room_id => 1, :group_id => 4, :teacher_id => 15, :subject_id => 16, :occupation => ''},
    {:parity => 0, :weekday_id => 4, :pair_id => 1, :room_id => 1, :group_id => 5, :teacher_id => 16, :subject_id => 17, :occupation => ''},
    {:parity => 0, :weekday_id => 4, :pair_id => 2, :room_id => 1, :group_id => 5, :teacher_id => 17, :subject_id => 18, :occupation => ''},
    {:parity => 0, :weekday_id => 4, :pair_id => 3, :room_id => 1, :group_id => 5, :teacher_id => 18, :subject_id => 19, :occupation => 'лаб.работа'},
    {:parity => 0, :weekday_id => 4, :pair_id => 4, :room_id => 1, :group_id => 5, :teacher_id => 19, :subject_id => 20, :occupation => 'лаб.работа'},
    {:parity => 0, :weekday_id => 4, :pair_id => 1, :room_id => 1, :group_id => 6, :teacher_id => 21, :subject_id => 21, :occupation => 'лаб.работа'},
    {:parity => 0, :weekday_id => 4, :pair_id => 2, :room_id => 1, :group_id => 6, :teacher_id => 20, :subject_id => 22, :occupation => 'лаб.работа'},
    {:parity => 0, :weekday_id => 4, :pair_id => 3, :room_id => 1, :group_id => 6, :teacher_id => 22, :subject_id => 23, :occupation => 'лаб.работа'},
    {:parity => 0, :weekday_id => 4, :pair_id => 4, :room_id => 1, :group_id => 6, :teacher_id => 23, :subject_id => 24, :occupation => 'лаб.работа'},
    {:parity => 0, :weekday_id => 5, :pair_id => 1, :room_id => 1, :group_id => 2, :teacher_id => 1, :subject_id => 1, :occupation => ''},
    {:parity => 0, :weekday_id => 5, :pair_id => 2, :room_id => 1, :group_id => 2, :teacher_id => 2, :subject_id => 2, :occupation => 'лекция'},
    {:parity => 0, :weekday_id => 5, :pair_id => 3, :room_id => 1, :group_id => 2, :teacher_id => 3, :subject_id => 3, :occupation => 'лекция'} , 
    {:parity => 0, :weekday_id => 5, :pair_id => 4, :room_id => 1, :group_id => 2, :teacher_id => 4, :subject_id => 4, :occupation => 'лекция'},
    {:parity => 0, :weekday_id => 5, :pair_id => 1, :room_id => 1, :group_id => 1, :teacher_id => 5, :subject_id => 5, :occupation => 'лекция'},
    {:parity => 0, :weekday_id => 5, :pair_id => 2, :room_id => 1, :group_id => 1, :teacher_id => 6, :subject_id => 6, :occupation => 'лекция'},
    {:parity => 0, :weekday_id => 5, :pair_id => 3, :room_id => 1, :group_id => 1, :teacher_id => 6, :subject_id => 7, :occupation => 'лекция'},
    {:parity => 0, :weekday_id => 5, :pair_id => 4, :room_id => 1, :group_id => 1, :teacher_id => 7, :subject_id => 8, :occupation => 'лекция'},
    {:parity => 0, :weekday_id => 5, :pair_id => 1, :room_id => 1, :group_id => 3, :teacher_id => 8, :subject_id => 9, :occupation => 'лекция'},
    {:parity => 0, :weekday_id => 5, :pair_id => 2, :room_id => 1, :group_id => 3, :teacher_id => 9, :subject_id => 10, :occupation => 'лекция'},
    {:parity => 0, :weekday_id => 5, :pair_id => 3, :room_id => 1, :group_id => 3, :teacher_id => 10, :subject_id => 11, :occupation => ''},
    {:parity => 0, :weekday_id => 5, :pair_id => 4, :room_id => 1, :group_id => 3, :teacher_id => 11, :subject_id => 12, :occupation => ''},
    {:parity => 0, :weekday_id => 5, :pair_id => 1, :room_id => 1, :group_id => 4, :teacher_id => 12, :subject_id => 13, :occupation => ''},
    {:parity => 0, :weekday_id => 5, :pair_id => 2, :room_id => 1, :group_id => 4, :teacher_id => 13, :subject_id => 14, :occupation => 'практика'},
    {:parity => 0, :weekday_id => 5, :pair_id => 3, :room_id => 1, :group_id => 4, :teacher_id => 14, :subject_id => 15, :occupation => 'практика'},
    {:parity => 0, :weekday_id => 5, :pair_id => 4, :room_id => 1, :group_id => 4, :teacher_id => 15, :subject_id => 16, :occupation => 'практика'},
    {:parity => 0, :weekday_id => 5, :pair_id => 1, :room_id => 1, :group_id => 5, :teacher_id => 16, :subject_id => 17, :occupation => 'практика'},
    {:parity => 0, :weekday_id => 5, :pair_id => 2, :room_id => 1, :group_id => 5, :teacher_id => 17, :subject_id => 18, :occupation => 'практика'},
    {:parity => 0, :weekday_id => 5, :pair_id => 3, :room_id => 1, :group_id => 5, :teacher_id => 18, :subject_id => 19, :occupation => 'практика'},
    {:parity => 0, :weekday_id => 5, :pair_id => 4, :room_id => 1, :group_id => 5, :teacher_id => 19, :subject_id => 20, :occupation => ''},
    {:parity => 0, :weekday_id => 5, :pair_id => 1, :room_id => 1, :group_id => 6, :teacher_id => 21, :subject_id => 21, :occupation => ''},
    {:parity => 0, :weekday_id => 5, :pair_id => 2, :room_id => 1, :group_id => 6, :teacher_id => 20, :subject_id => 22, :occupation => ''},
    {:parity => 0, :weekday_id => 5, :pair_id => 3, :room_id => 1, :group_id => 6, :teacher_id => 22, :subject_id => 23, :occupation => ''},
    {:parity => 0, :weekday_id => 5, :pair_id => 4, :room_id => 1, :group_id => 6, :teacher_id => 23, :subject_id => 24, :occupation => ''},
    {:parity => 0, :weekday_id => 6, :pair_id => 1, :room_id => 1, :group_id => 2, :teacher_id => 1, :subject_id => 1, :occupation => ''},
    {:parity => 0, :weekday_id => 6, :pair_id => 2, :room_id => 1, :group_id => 2, :teacher_id => 2, :subject_id => 2, :occupation => ''},
    {:parity => 0, :weekday_id => 6, :pair_id => 3, :room_id => 1, :group_id => 2, :teacher_id => 3, :subject_id => 3, :occupation => ''} , 
    {:parity => 0, :weekday_id => 6, :pair_id => 4, :room_id => 1, :group_id => 2, :teacher_id => 4, :subject_id => 4, :occupation => ''},
    {:parity => 0, :weekday_id => 6, :pair_id => 1, :room_id => 1, :group_id => 1, :teacher_id => 5, :subject_id => 5, :occupation => ''},
    {:parity => 0, :weekday_id => 6, :pair_id => 2, :room_id => 1, :group_id => 1, :teacher_id => 6, :subject_id => 6, :occupation => ''},
    {:parity => 0, :weekday_id => 6, :pair_id => 3, :room_id => 1, :group_id => 1, :teacher_id => 6, :subject_id => 7, :occupation => ''},
    {:parity => 0, :weekday_id => 6, :pair_id => 4, :room_id => 1, :group_id => 1, :teacher_id => 7, :subject_id => 8, :occupation => ''},
    {:parity => 0, :weekday_id => 6, :pair_id => 1, :room_id => 1, :group_id => 3, :teacher_id => 8, :subject_id => 9, :occupation => ''},
    {:parity => 0, :weekday_id => 6, :pair_id => 2, :room_id => 1, :group_id => 3, :teacher_id => 9, :subject_id => 10, :occupation => ''},
    {:parity => 0, :weekday_id => 6, :pair_id => 3, :room_id => 1, :group_id => 3, :teacher_id => 10, :subject_id => 11, :occupation => ''},
    {:parity => 0, :weekday_id => 6, :pair_id => 4, :room_id => 1, :group_id => 3, :teacher_id => 11, :subject_id => 12, :occupation => ''},
    {:parity => 0, :weekday_id => 6, :pair_id => 1, :room_id => 1, :group_id => 4, :teacher_id => 12, :subject_id => 13, :occupation => ''},
    {:parity => 0, :weekday_id => 6, :pair_id => 2, :room_id => 1, :group_id => 4, :teacher_id => 13, :subject_id => 14, :occupation => ''},
    {:parity => 0, :weekday_id => 6, :pair_id => 3, :room_id => 1, :group_id => 4, :teacher_id => 14, :subject_id => 15, :occupation => ''},
    {:parity => 0, :weekday_id => 6, :pair_id => 4, :room_id => 1, :group_id => 4, :teacher_id => 15, :subject_id => 16, :occupation => ''},
    {:parity => 0, :weekday_id => 6, :pair_id => 1, :room_id => 1, :group_id => 5, :teacher_id => 16, :subject_id => 17, :occupation => ''},
    {:parity => 0, :weekday_id => 6, :pair_id => 2, :room_id => 1, :group_id => 5, :teacher_id => 17, :subject_id => 18, :occupation => ''},
    {:parity => 0, :weekday_id => 6, :pair_id => 3, :room_id => 1, :group_id => 5, :teacher_id => 18, :subject_id => 19, :occupation => ''},
    {:parity => 0, :weekday_id => 6, :pair_id => 4, :room_id => 1, :group_id => 5, :teacher_id => 19, :subject_id => 20, :occupation => ''},
    {:parity => 0, :weekday_id => 6, :pair_id => 1, :room_id => 1, :group_id => 6, :teacher_id => 21, :subject_id => 21, :occupation => ''},
    {:parity => 0, :weekday_id => 6, :pair_id => 2, :room_id => 1, :group_id => 6, :teacher_id => 20, :subject_id => 22, :occupation => ''},
    {:parity => 0, :weekday_id => 6, :pair_id => 3, :room_id => 1, :group_id => 6, :teacher_id => 22, :subject_id => 23, :occupation => ''},
    {:parity => 0, :weekday_id => 6, :pair_id => 4, :room_id => 1, :group_id => 6, :teacher_id => 23, :subject_id => 24, :occupation => ''}
    ])
puts 'Stop adding schedules'

puts 'FINISHED'

