require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe WeekdaysController do

  # This should return the minimal set of attributes required to create a valid
  # Weekday. As you add validations to Weekday, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # WeekdaysController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all weekdays as @weekdays" do
      weekday = Weekday.create! valid_attributes
      get :index, {}, valid_session
      assigns(:weekdays).should eq([weekday])
    end
  end

  describe "GET show" do
    it "assigns the requested weekday as @weekday" do
      weekday = Weekday.create! valid_attributes
      get :show, {:id => weekday.to_param}, valid_session
      assigns(:weekday).should eq(weekday)
    end
  end

  describe "GET new" do
    it "assigns a new weekday as @weekday" do
      get :new, {}, valid_session
      assigns(:weekday).should be_a_new(Weekday)
    end
  end

  describe "GET edit" do
    it "assigns the requested weekday as @weekday" do
      weekday = Weekday.create! valid_attributes
      get :edit, {:id => weekday.to_param}, valid_session
      assigns(:weekday).should eq(weekday)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Weekday" do
        expect {
          post :create, {:weekday => valid_attributes}, valid_session
        }.to change(Weekday, :count).by(1)
      end

      it "assigns a newly created weekday as @weekday" do
        post :create, {:weekday => valid_attributes}, valid_session
        assigns(:weekday).should be_a(Weekday)
        assigns(:weekday).should be_persisted
      end

      it "redirects to the created weekday" do
        post :create, {:weekday => valid_attributes}, valid_session
        response.should redirect_to(Weekday.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved weekday as @weekday" do
        # Trigger the behavior that occurs when invalid params are submitted
        Weekday.any_instance.stub(:save).and_return(false)
        post :create, {:weekday => { "name" => "invalid value" }}, valid_session
        assigns(:weekday).should be_a_new(Weekday)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Weekday.any_instance.stub(:save).and_return(false)
        post :create, {:weekday => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested weekday" do
        weekday = Weekday.create! valid_attributes
        # Assuming there are no other weekdays in the database, this
        # specifies that the Weekday created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Weekday.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => weekday.to_param, :weekday => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested weekday as @weekday" do
        weekday = Weekday.create! valid_attributes
        put :update, {:id => weekday.to_param, :weekday => valid_attributes}, valid_session
        assigns(:weekday).should eq(weekday)
      end

      it "redirects to the weekday" do
        weekday = Weekday.create! valid_attributes
        put :update, {:id => weekday.to_param, :weekday => valid_attributes}, valid_session
        response.should redirect_to(weekday)
      end
    end

    describe "with invalid params" do
      it "assigns the weekday as @weekday" do
        weekday = Weekday.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Weekday.any_instance.stub(:save).and_return(false)
        put :update, {:id => weekday.to_param, :weekday => { "name" => "invalid value" }}, valid_session
        assigns(:weekday).should eq(weekday)
      end

      it "re-renders the 'edit' template" do
        weekday = Weekday.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Weekday.any_instance.stub(:save).and_return(false)
        put :update, {:id => weekday.to_param, :weekday => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested weekday" do
      weekday = Weekday.create! valid_attributes
      expect {
        delete :destroy, {:id => weekday.to_param}, valid_session
      }.to change(Weekday, :count).by(-1)
    end

    it "redirects to the weekdays list" do
      weekday = Weekday.create! valid_attributes
      delete :destroy, {:id => weekday.to_param}, valid_session
      response.should redirect_to(weekdays_url)
    end
  end

end
